### ISSUE TITLE
[Restore YouTube Username] it doesn't work

### ISSUE THREAD

**Issue by wiful10** [cyfung1031/userscript-supports#43] opened 2024-06-07 14:25 UTC
Some accounts work fine, some don't.

![111](https://github.com/cyfung1031/userscript-supports/assets/102317996/3e372739-c962-443d-bb7f-22611325a0e0)
![222](https://github.com/cyfung1031/userscript-supports/assets/102317996/ed9cf6ac-ad55-4ffa-8fbb-58854cb7ac6c)

**Comment by cyfung1031** [comment] 2024-06-07 15:52
Thanks for reporting. Fixed now.

**Comment by cyfung1031** [comment] 2024-06-11 14:57
@wiful10 Could you please confirm the issue is resolved or not?

**Comment by wiful10** [comment] 2024-06-15 22:36
Solved. Thank you.

**Closed** 2024-06-16 02:50 UTC
